# Generated by Django 4.0.2 on 2022-02-15 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itype', models.CharField(max_length=10)),
                ('iname', models.CharField(max_length=50)),
                ('inum', models.IntegerField(default=0)),
                ('idate', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge_app.user')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
