# Generated by Django 4.0.2 on 2022-02-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cicode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cidate',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='ciname',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='cinum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='citype',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
