# Generated by Django 4.0.2 on 2022-02-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_item_icode_user_cicode_user_cidate_user_ciname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.IntegerField(default=0),
        ),
    ]
