# Generated by Django 4.0.2 on 2022-02-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0003_user_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='idesc',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='cidesc',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='iname',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='itype',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
