# Generated by Django 4.0.2 on 2022-02-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0004_item_idesc_user_cidesc_alter_item_idate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choice',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
