# Generated by Django 4.0.2 on 2022-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0005_user_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cidate',
            field=models.DateTimeField(),
        ),
    ]
