# Generated by Django 4.0.2 on 2022-03-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0006_alter_item_idate_alter_user_cidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='idate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cidate',
            field=models.DateTimeField(null=True),
        ),
    ]
